inherit_mode:
  merge:
    - Exclude

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/*'
    - 'config/*.rb'
    - 'config/environments/*.rb'
    - 'db/*schema.rb'

Bundler/OrderedGems:
  Enabled: false

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/AlignParameters:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/EndAlignment:
  AutoCorrect: true

Layout/FirstParameterIndentation:
  Enabled: false

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/UselessAccessModifier:
  ContextCreatingMethods:
    - concerning

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - Gemfile
    - 'spec/**/*'
    - 'db/**/*'
  IgnoredPatterns: ['\A#']

Metrics/MethodLength:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Performance/TimesMap:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ClassAndModuleChildren:
  AutoCorrect: true

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier: # Enable if this moves forward: https://github.com/rubocop-hq/rubocop/issues/6149
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/MultilineBlockChain:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/MixinUsage:
  Enabled: false
